name: 'Test Report'
description: 'Saves the test reports'

runs:
  using: 'composite'
  steps:
    - uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          junit.xml
          coverage
          packages/*/coverage
